export enum IconName {
  angleDown = 'angle-down',
  arrowBack = 'arrow-back',
  arrowDown = 'arrow-down',
  arrowForward = 'arrow-forward',
  arrowUp = 'arrow-up',
  bookmarkFill = 'bookmark-fill',
  bookmarkOutline = 'bookmark-fill',
  calendar = 'calendar',
  chat = 'chat',
  checkmark = 'check',
  clock = 'clock',
  close = 'close',
  cloud = 'cloud',
  danger = 'danger',
  delete = 'delete',
  download = 'download',
  eyeOff = 'eye-off',
  eyeOn = 'eye-on',
  heartFill = 'heart-fill',
  heartOutline = 'heart-outline',
  info = 'info',
  label = 'label',
  lock = 'lock',
  mail = 'mail',
  mapPin = 'map-pin',
  menu = 'menu',
  more = 'more',
  person = 'person',
  phone = 'phone',
  plus = 'plus',
  search = 'search',
  starFill = 'star-fill',
  starHalf = 'star-half',
  starOutline = 'star-outline',
  success = 'success',
  thumbDownFill = 'thumb-down-fill',
  thumbDownOutline = 'thumb-down-outline',
  thumbUpFill = 'thumb-up-fill',
  thumbUpOutline = 'thumb-up-outline',
  today = 'today',
  upload = 'upload',
  warning = 'warning',
  zoomIn = 'zoom-in',
  zoomOut = 'zoom-out',
}

export enum ValidColors {
  gray0 = '#f9f9f9',
  gray1 = '#ecedee',
  gray2 = '#dfe0e2',
  gray3 = '#d1d3d4',
  gray4 = '#c1c3c6',
  gray5 = '#b0b3b6',
  gray6 = '#9ca0a4',
  gray7 = '#85898e',
  gray8 = '#676c72',
  gray9 = '#393f47',
  indigo0 = '#edecff',
  indigo1 = '#dad7ff',
  indigo2 = '#c3bfff',
  indigo3 = '#a9a3ff',
  indigo4 = '#877eff',
  indigo5 = '#5044ff',
  indigo6 = '#483de5',
  indigo7 = '#3e35c8',
  indigo8 = '#332ba4',
  indigo9 = '#241e73',
}

export interface IconProps {
  name: IconName;
  size: 12 | 18 | 24 | 32 | 40 | 48 | 56 | 64 | 72;
  animate?: boolean | { delay: number };
  color?: ValidColors;
  onClick?: (e: React.MouseEvent) => void;
}
